# Generated by Django 2.1.5 on 2019-03-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('Message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='powerquestionbank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.CharField(max_length=50)),
                ('icontains', models.CharField(max_length=50)),
                ('rubric', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=500)),
                ('option', models.CharField(max_length=500)),
            ],
        ),
    ]
